
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Employee_db
    username: root
    password: root
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update


logging:
  level:
    org.springframework: info